### ISSUE TITLE
IOS Images not showing

### ISSUE THREAD

**Issue by ryanwrtong** [graceoncampus/goc-app#3]
**Description**:
Images are not showing up on the IOS VM, such as the sermon player images, blog images, and GOC logo (announcements) images.

**Acceptance Criteria**:
1. IOS images are displayed, including the examples listed in the description
2. IOS app builds properly so that it can be ready for release

**Comments**:
Could be related to updating to a newer IOS version or XCode version, since they were working before with no changes. This could just be a VM issue on my end, so make sure to test on a physical iPhone if possible. I will likely release to App Store after this fix, so if you encounter any other bugs along the way, let me know.

**Comment by hayleydmartinez** [comment]
Fixed!
